name: Pluralith Workflox
run-name: Pluralith Workflow
on:
    workflow_dispatch:
jobs:
    pluralith:
        name: Pluralith Graph Generation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Check whether the .aws/configuration and credentials file exists
              run: |
                    cd ~/.aws
                    ls
                