name: Pluralith Workflox
run-name: Pluralith Workflow
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    pluralith:
        name: Pluralith Graph Generation
        runs-on: ubuntu-latest
        steps:
            - name: Update 
              run: sudo apt-get update
            - name: Checkout
              uses: actions/checkout@v4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: us-east-1
            - name: Mkdir for Pluralith Executables
              run: mkdir pluralith-executables && ls -la
            - name: Download Pluralith Executables from S3 bucket
              run: aws s3 sync s3://pluralith-executables/ ./pluralith-executables
            - name: Change permissions for Pluralith Executables
              run: chmod +x ./pluralith-executables/pluralith && chmod +x ./pluralith-executables/pluralith-cli-graphing
            - name: Check executables have been downloaded and permissions have been set
              run: ls -la ./pluralith-executables
            - name: Add pluralith to PATH
              run: mv ./pluralith-executables/pluralith /usr/local/bin/pluralith
            - name: Pluralith login
              run: pluralith login --api-key ${{ secrets.PLURALITH_API_KEY }}
            - name: Check whether the Pluralith directory exists
              run: ls -la ~/Pluralith
            - name: Move pluralith-cli-graphing to the Pluralith directory
              run: mv ./pluralith-executables/pluralith-cli-graphing ~/Pluralith/bin/
            - name: Check whether the pluralith-cli-graphing executable has been moved to the Pluralith directory
              run: ls -la ~/Pluralith/bin/
            - name: Generate Pluralith Graph
              run: ls -la
                