name: Pluralith Workflox
run-name: Pluralith Workflow
on:
    workflow_dispatch:
jobs:
    pluralith:
        name: Pluralith Graph Generation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Check whether the .aws/configuration and credentials file exists
              run: |
                  if [ -f ~/.aws/config ]; then
                      echo "AWS config file exists"
                  else
                      echo "AWS config file does not exist"
                  fi
                  if [ -f ~/.aws/credentials ]; then
                      echo "AWS credentials file exists"
                  else
                      echo "AWS credentials file does not exist"
                  fi